name: CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check if repository exists
        id: repo_check
        run: |
          if [ -d "~/apps/profit-plus-api-ga" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        shell: bash

      - name: Checkout repository
        if: steps.repo_check.outputs.exists == 'false'
        uses: actions/checkout@v2

      - name: Update repository
        if: steps.repo_check.outputs.exists == 'true'
        run: |
          cd path/to/your/repository
          git pull origin schema

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/apps/profit-plus-api-ga
            git status
            npm install --omit=dev
            pm2 restart src/Main.js
