name: CD
on:
  push:
    branches: [ "main", "schema" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Check for existing repository
        run: |
          if [ -d ~/apps/profit-plus-api-ga/.git ]; then
            echo "Repository exists, pulling changes..."
          else
            echo "Repository not found, cloning..."
            cd ~/apps
            git clone https://github.com/royhanantariksaaa/profit-plus-api-ga.git -b schema 
          fi
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/apps/profit-plus-api-ga
            git pull origin schema
            git status
            npm install --omit=dev
            pm2 restart src/Main.js
