name: CD
on:
  push:
    branches: [ "main", "schema" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT}}
          script: |
            if [ -d ~/apps/profit-plus-api-ga/.git ]; then
              echo "Repository exists, pulling changes..."
              cd ~/apps/profit-plus-api-ga
              git checkout
              git pull --rebase origin schema
            else
              echo "Repository not found, cloning..."
              cd ~/apps
              git clone https://github.com/royhanantariksaaa/profit-plus-api-ga.git -b schema 
            fi
            cd ~/apps/profit-plus-api-ga
            git status
            npm install --omit=dev
            if pm2 list | grep profitplus; then
              echo "Process 'profitplus' already running with pm2."
              pm2 restart 'profitplus' --update-env
            else
              echo "Process 'profitplus' not found with pm2."
              pm2 start src/Main.js --name "profitplus" --update-env
            fi
            pm2 save
            
