name: CD
on:
  push:
    branches: [ "main", "schema" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT}}
          script: |
            if [ -d ~/apps/profit-plus-api-ga/.git ]; then
              echo "Repository exists, pulling changes..."
              cd ~/apps/profit-plus-api-ga
              git checkout
              git pull origin schema
            else
              echo "Repository not found, cloning..."
              cd ~/apps
              git clone https://github.com/royhanantariksaaa/profit-plus-api-ga.git -b schema 
            fi
            cd ~/apps/profit-plus-api-ga
            git status
            npm install --omit=dev
            pm2 restart src/Main.js --cwd ~/apps/profit-plus-api-ga
